### PR TITLE
Ensure module source file names are accepted up to alphanum

### LINKED ISSUE #750: Module names containing a cedilla fail to register
While trying to interpret a file calling a module `Français`, I got this error:

```
(catdev) romain@enclume:~/inria/cat_root/catala-language-server$ clerk run test-case-parser/examples/test_case_french.catala_fr -s French_test
[1/2] <catala> interpret French_test ⇐ _build/test-case-parser/examples/test_case_french.catala_fr
┌─[ERROR]─
│
│  Module Français was loaded from file "test-case-parser/examples/Français.cmxs" but did not register properly, there is something wrong in its code.
│
└─
```

### PR DESCRIPTION
**Pull request by AltGr**
Mainly, updates File.scan to lookup files after projection to ASCII

Closes #750

### CODE REVIEW

File: compiler/driver.ml [hunk 1]
```diff
@@ -1363,6 +1362,9 @@ module Commands = struct
   let depends_cmd =
     Cmd.v
       (Cmd.info "depends" ~man:Cli.man_base
+         ~deprecated:
```
Comment (denismerigoux) [inline compiler/driver.ml:1365]: If this is deprecated, why not remove the `depends` command entirely? It's weird to have deprecated commands in a 1.0.0 :)
